# Generated by Django 3.1.5 on 2021-01-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latesttrack',
            name='title',
            field=models.CharField(default='Wither', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='latestvideo',
            name='title',
            field=models.CharField(default='Wither', max_length=250),
            preserve_default=False,
        ),
    ]
