# Generated by Django 3.1.5 on 2021-01-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20210118_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LatestTrack',
            new_name='Tracks',
        ),
        migrations.RenameModel(
            old_name='LatestVideo',
            new_name='Videos',
        ),
    ]
