# Generated by Django 3.1.5 on 2021-01-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20210118_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tracks',
            new_name='Track',
        ),
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
