# Generated by Django 3.1.5 on 2021-01-19 19:20

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20210118_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='dfhgh'),
            preserve_default=False,
        ),
    ]
