# Generated by Django 3.1.5 on 2021-01-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_auto_20210119_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='wither', max_length=250),
            preserve_default=False,
        ),
    ]
