# Generated by Django 3.1.5 on 2021-01-20 14:14

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
