# Generated by Django 3.1.5 on 2021-01-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_auto_20210123_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
