# Generated by Django 3.1.5 on 2021-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20210123_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
